services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: queupy
      POSTGRES_PASSWORD: queupy
      POSTGRES_DB: queupy
    restart: always

  consumer1:
    image: queupy
    command: ["python", "examples/consumer.py"]
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs

  consumer2:
    image: queupy
    command: ["python", "examples/consumer.py"]
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs

  producer:
    image: queupy
    command: ["python", "examples/producer.py"]
    depends_on:
      - postgres

