name: Python Package CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install setuptools wheel twine bump2version

      - name: Run tests
        run: |
          pytest  # Assuming you use pytest for testing

      - name: Bump version
        id: bump_version
        run: |
          bump2version patch  # Update 'patch' to 'minor' or 'major' as needed

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*

      - name: Push new version tag to GitHub
        run: |
          git push --follow-tags

